// convert from json to typescript
export const voices = [
  {
    languageCodes: ["af-ZA"],
    name: "af-ZA-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["am-ET"],
    name: "am-ET-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aster",
  },
  {
    languageCodes: ["am-ET"],
    name: "am-ET-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abel",
  },
  {
    languageCodes: ["am-ET"],
    name: "am-ET-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aida",
  },
  {
    languageCodes: ["am-ET"],
    name: "am-ET-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amanuel",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amira",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ahmed",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ali",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayah",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abdullah",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abdul",
  },
  {
    languageCodes: ["ar-XA"],
    name: "ar-XA-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amina",
  },
  {
    languageCodes: ["bg-BG"],
    name: "bg-BG-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Borislava",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Bipasha",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Bijoy",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Binita",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Biswajit",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Bristi",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Biplab",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Bithi",
  },
  {
    languageCodes: ["bn-IN"],
    name: "bn-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Bikash",
  },
  {
    languageCodes: ["ca-ES"],
    name: "ca-ES-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Cristina",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mei",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ming",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Min",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Meng",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Miao",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mingyu",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Minjun",
  },
  {
    languageCodes: ["cmn-CN"],
    name: "cmn-CN-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Meixi",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mei",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ming",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Min",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Miao",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mingyu",
  },
  {
    languageCodes: ["cmn-TW"],
    name: "cmn-TW-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Minjun",
  },
  {
    languageCodes: ["cs-CZ"],
    name: "cs-CZ-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Cecilie",
  },
  {
    languageCodes: ["cs-CZ"],
    name: "cs-CZ-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Cecilka",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Neural2-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ditte",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dorte",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dina",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ditte",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["da-DK"],
    name: "da-DK-Wavenet-E",
    " ssmlGender": "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dina",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Neural2-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dina",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dominik",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dominik",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dina",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Standard-H",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Studio-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dominik",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Studio-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dominik",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Dina",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["de-DE"],
    name: "de-DE-Wavenet-H",
    "ssml Gender": "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["el-GR"],
    name: "el-GR-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleni",
  },
  {
    languageCodes: ["el-GR"],
    name: "el-GR-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleni",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayla",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-News-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-News-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-News-G",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Elijah",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayla",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayla",
  },
  {
    languageCodes: ["en-AU"],
    name: "en-AU-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abigail",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexander",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Neural2-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB- News-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-H",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleanor",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-I",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Evie",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-J",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-K",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Edward",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-L",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Elijah",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-News-M",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ellis",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abigail",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexander",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Standard-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Studio-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Elijah",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Studio-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Evie",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Abigail",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexander",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-GB"],
    name: "en-GB-Wavenet-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Neural2-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Standard-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["en-IN"],
    name: "en-IN-Wavenet-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Casual-K",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Kevin",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Journey-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Journey-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Journey-O",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-A",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleanor",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-H",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Evie",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-I",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Neural2-J",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Edward",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-News-K",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-News-L",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    " humanName": "Eva",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-News-N",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Elijah",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-A",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexander",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleanor",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-H",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Evie",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-I",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Standard-J",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Edward",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Studio-O",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Olivia",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Studio-Q",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Quincy",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-A",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Austin",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Asher",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ava",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexander",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Emily",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eva",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eleanor",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-H",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Evie",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-I",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ethan",
  },
  {
    languageCodes: ["en-US"],
    name: "en-US-Wavenet-J",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Edward",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alba",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alicia",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Neural2-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antonio",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alberto",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alba",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alicia",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antonio",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Standard-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Studio-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Cristina",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Studio-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Francisco",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alba",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alicia",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Wavenet-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antonio",
  },
  {
    languageCodes: ["es-ES"],
    name: "es-ES-Wavenet-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alberto",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-News-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniel",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-News-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diego",
  },
  {
    languageCodes: ["es-US"],
    name: " es-US-News-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Daniela",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-News-G",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Diana",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Eduardo",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alberto",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Studio-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Benjamin",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alejandro",
  },
  {
    languageCodes: ["es-US"],
    name: "es-US-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alberto",
  },
  {
    languageCodes: ["eu-ES"],
    name: "eu-ES-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ane",
  },
  {
    languageCodes: ["fi-FI"],
    name: "fi-FI-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aada",
  },
  {
    languageCodes: ["fi-FI"],
    name: "fi-FI-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aada",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Standard-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Angel",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arnel",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arnold",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Wavenet-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Angel",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arnel",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-PH-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arnold",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-ph-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["fil-PH"],
    name: "fil-ph-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arnel",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-CA"],
    name: "fr-CA-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anaïs",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Neural2-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Adèle",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Polyglot-1",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Étienne",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anaïs",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Adèle",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amandine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Standard-G",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Étienne",
  },
  {
    languageCodes: ["fr-FR"],
    " name": "fr-FR-Studio-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anaïs",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Studio-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "David",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anaïs",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antoine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurélie",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alexandre",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Adèle",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-F",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amandine",
  },
  {
    languageCodes: ["fr-FR"],
    name: "fr-FR-Wavenet-G",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Étienne",
  },
  {
    languageCodes: ["gl-ES"],
    name: "gl-ES-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["gu-IN"],
    name: "gu-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayelet",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ariel",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Adi",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amir",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayelet",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ariel",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Wavenet-C ",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Adi",
  },
  {
    languageCodes: ["he-IL"],
    name: "he-IL-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amir",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Neural2-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Standard-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryan",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["hi-IN"],
    name: "hi-IN-Wavenet-F",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["hu-HU"],
    name: "hu-HU-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["hu-HU"],
    name: "hu-HU-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayu",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryo",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arief",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisyah",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayu",
  },
  {
    languageCodes: ["id-ID"],
    "name ": "id-ID-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aryo",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arief",
  },
  {
    languageCodes: ["id-ID"],
    name: "id-ID-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisyah",
  },
  {
    languageCodes: ["is-IS"],
    name: "is-IS-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ásta",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessia",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandro",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessia",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Standard-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandro",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessia",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Wavenet-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandro",
  },
  {
    languageCodes: ["it-IT"],
    name: "it-IT-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrea",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Neural2-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mizuki",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Kaito",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Takeru",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mizuki",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Standard-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Yui",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Kaito",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Takeru",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Mizuki",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Wavenet-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Yui",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: " Kaito",
  },
  {
    languageCodes: ["ja-JP"],
    name: "ja-JP-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Takeru",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["kn-IN"],
    name: "kn-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jihee",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Neural2-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jiyeon",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Neural2-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jinwoo",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jihee",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Standard-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jiyeon",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jinwoo",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Junho",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jihee",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Wavenet-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jiyeon",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Jinwoo",
  },
  {
    languageCodes: ["ko-KR"],
    name: "ko-KR-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Junho",
  },
  {
    languageCodes: ["lt-LT"],
    name: "lt-LT-Standard-A",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrius",
  },
  {
    languageCodes: ["lv-LV"],
    name: "lv-LV-Standard-A",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Artūrs",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit ",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["ml-IN"],
    name: "ml-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["mr-IN"],
    name: "mr-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisyah",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arief",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayu",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arif",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisyah",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arief",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayu",
  },
  {
    languageCodes: ["ms-MY"],
    name: "ms-MY-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arif",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreas",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Standard-E",
    " ssmlGender": "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreas",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nb-NO"],
    name: "nb-NO-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["nl-BE"],
    name: "nl-BE-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nl-BE"],
    name: "nl-BE-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nl-BE"],
    name: "nl-BE-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nl-BE"],
    name: "nl-BE-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["nl-NL"],
    name: "nl-NL-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Wavenet-A",
    "ssmlGender ": "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aaradhya",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["pa-IN"],
    name: "pa-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Agnieszka",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrzej",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Artur",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aleksandra",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anna",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Agnieszka",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrzej",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Artur",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aleksandra",
  },
  {
    languageCodes: ["pl-PL"],
    name: "pl-PL-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anna",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Neural2-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antônio",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandra",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antônio",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandra",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andréa",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Standard-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antônio",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Waven et-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alessandra",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andréa",
  },
  {
    languageCodes: ["pt-BR"],
    name: "pt-BR-Wavenet-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antônio",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Standard-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andréa",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Antônio",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "André",
  },
  {
    languageCodes: ["pt-PT"],
    name: "pt-PT-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andréa",
  },
  {
    languageCodes: ["ro-RO"],
    name: "ro-RO-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreea",
  },
  {
    languageCodes: ["ro-RO"],
    name: "ro-RO-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreea",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alina",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrey",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anastasia",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anton",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Standard-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anna",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alina",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andrey",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anastasia",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anton",
  },
  {
    languageCodes: ["ru-RU"],
    name: "ru-RU-Wavenet-E",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anna",
  },
  {
    languageCodes: ["sk-SK"],
    name: "sk-SK-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alica",
  },
  {
    languageCodes: ["sk-SK"],
    name: "sk-S K-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Alica",
  },
  {
    languageCodes: ["sr-RS"],
    name: "sr-RS-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ana",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Standard-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Standard-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreas",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Astrid",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Wavenet-B",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aurora",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Wavenet-C",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arne",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anita",
  },
  {
    languageCodes: ["sv-SE"],
    name: "sv-SE-Wavenet-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Andreas",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ananya",
  },
  {
    languageCodes: ["ta-IN"],
    name: "ta-IN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Arjun",
  },
  {
    languageCodes: ["te-IN"],
    name: "te-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aishwarya",
  },
  {
    languageCodes: ["te-IN"],
    name: "te-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["th-TH"],
    name: "th-TH-Neural2-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Achara",
  },
  {
    languageCodes: ["th-TH"],
    name: "th-TH-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Achara",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Standard-A",
    ssmlGender: "FEMALE",
    "natural SampleRateHertz": 24000,
    humanName: "Ayşe",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ahmet",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aslı",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Standard-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayşe",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Standard-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ahmet",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayşe",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ahmet",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aslı",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Wavenet-D",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ayşe",
  },
  {
    languageCodes: ["tr-TR"],
    name: "tr-TR-Wavenet-E",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Ahmet",
  },
  {
    languageCodes: ["uk-UA"],
    name: "uk-UA-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anastasia",
  },
  {
    languageCodes: ["uk-UA"],
    name: "uk-UA-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anastasia",
  },
  {
    languageCodes: ["ur-IN"],
    name: "ur-IN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["ur-IN"],
    name: "ur-IN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["ur-IN"],
    name: "ur-IN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Aisha",
  },
  {
    languageCodes: ["ur-IN"],
    name: "ur-IN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Amit",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Neural2-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "An",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Neural2-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "An",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Wavenet-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "An",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Wavenet-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Wavenet-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    "human Name": "Anh",
  },
  {
    languageCodes: ["vi-VN"],
    name: "vi-VN-Wavenet-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Anh",
  },
  {
    languageCodes: ["yue-HK"],
    name: "yue-HK-Standard-A",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Wing",
  },
  {
    languageCodes: ["yue-HK"],
    name: "yue-HK-Standard-B",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Wai",
  },
  {
    languageCodes: ["yue-HK"],
    name: "yue-HK-Standard-C",
    ssmlGender: "FEMALE",
    naturalSampleRateHertz: 24000,
    humanName: "Wing",
  },
  {
    languageCodes: ["yue-HK"],
    name: "yue-HK-Standard-D",
    ssmlGender: "MALE",
    naturalSampleRateHertz: 24000,
    humanName: "Wai",
  },
];
